apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached-api
  name: memcached-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  # - port: 11211
  #   protocol: TCP
  #   targetPort: 11211
  #   nodePort: 30001
  type: NodePort
  selector:
    app: memcached-api
status:
  loadBalancer: {}
